---
- name: Update web servers
  hosts: devservers
  remote_user: root
  vars:
    DOCKER_COMPOSE_VERSION: "1.25.1"
    DOCKER_PACKAGES:
      - apt-transport-https
      - curl
  

  tasks:
  - name: Leaving a mark
    vars:
      ansible_python_interpreter: /usr/bin/python3
    command: "touch /tmp/ansible_was_here"

  - name: Install packages needed for Docker
    apt:
      name: "{{ DOCKER_PACKAGES }}"
      state: present
      force_apt_get: "yes"

  - name: Save the current Ubuntu release version into a variable
    shell: lsb_release -cs
    register: ubuntu_version

  - name: Show output of ubuntu version
    debug:
      msg: "Ubuntu version output: {{ubuntu_version.stdout}}"


  - name: Test Docker with hello world example
    shell: "docker run hello-world"
    register: hello_world_output

  - name: Show output of hello word example
    debug:
      msg: "Container Output: {{hello_world_output.stdout}}"

  - name: Save all docker instances
    shell: docker ps -a
    register: docker_ps_a_output

  - name: Show output of all docker instances
    debug:
      msg: "Docker instances output: {{docker_ps_a_output.stdout}}"

  